"""add_preprocessing_fields

Revision ID: 5b4a90e7b081
Revises: 38de3f877419
Create Date: 2026-07-25 06:59:12.239949

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '5b4a90e7b081'
down_revision: str | None = '38de3f877419'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: manual create() is required here because add_column does not implicitly dispatch CREATE TYPE like create_table does.
    processingstatusenum = postgresql.ENUM('raw', 'processing', 'processed', 'skipped_non_english', 'failed', name='processingstatusenum')
    processingstatusenum.create(op.get_bind())
    op.add_column('articles', sa.Column('processing_status', sa.Enum('raw', 'processing', 'processed', 'skipped_non_english', 'failed', name='processingstatusenum'), server_default='raw', nullable=False))
    op.add_column('articles', sa.Column('cleaned_content', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('canonical_article_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('articles', sa.Column('domain', sa.String(), nullable=True))
    op.add_column('articles', sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'articles', 'articles', ['canonical_article_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_column('articles', 'processed_at')
    op.drop_column('articles', 'domain')
    op.drop_column('articles', 'word_count')
    op.drop_column('articles', 'canonical_article_id')
    op.drop_column('articles', 'cleaned_content')
    op.drop_column('articles', 'processing_status')
    # Note: manual drop() is required here because drop_column does not implicitly dispatch DROP TYPE like drop_table does.
    processingstatusenum = postgresql.ENUM('raw', 'processing', 'processed', 'skipped_non_english', 'failed', name='processingstatusenum')
    processingstatusenum.drop(op.get_bind())
    # ### end Alembic commands ###
