"""add_nlp_fields

Revision ID: 723ad59c617a
Revises: 5b4a90e7b081
Create Date: 2026-07-25 12:07:29.497922

"""
from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '723ad59c617a'
down_revision: str | None = '5b4a90e7b081'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")
    op.create_table('claims',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('claim_text', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=768), nullable=True),
    sa.Column('extracted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_article_id'), 'claims', ['article_id'], unique=False)
    op.create_table('claim_entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('entity_text', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('start_char', sa.Integer(), nullable=True),
    sa.Column('end_char', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_entities_claim_id'), 'claim_entities', ['claim_id'], unique=False)
    
    # Note: manual create() is required here because add_column does not implicitly dispatch CREATE TYPE like create_table does.
    nlpstatusenum = postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'skipped', name='nlpstatusenum')
    nlpstatusenum.create(op.get_bind())
    op.add_column('articles', sa.Column('nlp_status', sa.Enum('pending', 'processing', 'completed', 'failed', 'skipped', name='nlpstatusenum'), server_default='pending', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'nlp_status')
    
    # Note: manual drop() is required here because drop_column does not implicitly dispatch DROP TYPE like drop_table does.
    nlpstatusenum = postgresql.ENUM('pending', 'processing', 'completed', 'failed', 'skipped', name='nlpstatusenum')
    nlpstatusenum.drop(op.get_bind())
    
    op.drop_index(op.f('ix_claim_entities_claim_id'), table_name='claim_entities')
    op.drop_table('claim_entities')
    op.drop_index(op.f('ix_claims_article_id'), table_name='claims')
    op.drop_table('claims')
    # ### end Alembic commands ###
