"""add_evolution_fields

Revision ID: 93dd360063d7
Revises: 723ad59c617a
Create Date: 2026-07-25 13:43:38.555251

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '93dd360063d7'
down_revision: str | None = '723ad59c617a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('claim_cluster_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('algorithm_params', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('claims_in_corpus', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('claim_cluster_assignments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('claim_id', sa.UUID(), nullable=False),
    sa.Column('cluster_run_id', sa.UUID(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_label', sa.String(), nullable=True),
    sa.Column('topic_keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['cluster_run_id'], ['claim_cluster_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_cluster_assignments_claim_id'), 'claim_cluster_assignments', ['claim_id'], unique=False)
    op.create_index(op.f('ix_claim_cluster_assignments_cluster_run_id'), 'claim_cluster_assignments', ['cluster_run_id'], unique=False)
    op.create_table('claim_relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('from_claim_id', sa.UUID(), nullable=False),
    sa.Column('to_claim_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('SIMILAR_TO', 'EVOLVED_FROM', name='relationshiptypeenum'), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['from_claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_claim_id'], ['claims.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claim_relationships_from_claim_id'), 'claim_relationships', ['from_claim_id'], unique=False)
    op.create_index(op.f('ix_claim_relationships_to_claim_id'), 'claim_relationships', ['to_claim_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_claim_relationships_to_claim_id'), table_name='claim_relationships')
    op.drop_index(op.f('ix_claim_relationships_from_claim_id'), table_name='claim_relationships')
    op.drop_table('claim_relationships')
    op.drop_index(op.f('ix_claim_cluster_assignments_cluster_run_id'), table_name='claim_cluster_assignments')
    op.drop_index(op.f('ix_claim_cluster_assignments_claim_id'), table_name='claim_cluster_assignments')
    op.drop_table('claim_cluster_assignments')
    op.drop_table('claim_cluster_runs')
    # ### end Alembic commands ###
